default: &default
  adapter: postgresql
  encoding: unicode
  <% if ENV['POSTGRES_HOSTNAME'] %>
  host: <%= ENV['POSTGRES_HOSTNAME'] %>
  <% end %>  
  pool: 5
  port: 5432
  <% if ENV['POSTGRES_USERNAME'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  <% end %>
  <% if ENV['POSTGRES_PASSWORD'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  <% end %>

development: &development
  <<: *default

staging:
  <<: *default

preproduction:
  <<: *default
  <% if ENV['SECRET_KEY_BASE'] %>
  secret_key_base: '<%= ENV.fetch("SECRET_KEY_BASE") %>'
  <% end %>
  <% if ENV['POSTGRES_DATABASE'] %>
  database: <%= ENV['POSTGRES_DATABASE'] %>
  <% end %>

production:
  <<: *default


test:
  url: '<%= ENV.fetch("DATABASE_TEST_URL", "postgres://change-me") %>'
